<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Eloquent::unguard();

		$this->call('RoleTableSeeder');
		$this->call('UserTableSeeder');
            $this->call('OrderStatusTableSeeder');
		$this->call('MerchantTableSeeder');
		$this->call('CategoryTableSeeder');
            $this->call('BrandTableSeeder');
            $this->call('BrandCategoryTableSeeder');
	}    

}


class RoleTableSeeder extends seeder {
	public function run(){
		DB::table('merchants')->delete();
		DB::table('users')->delete();
		DB::table('roles')->delete();
		DB::table('roles')->insert(array(
			 array('id' => 1,'title' => 'Administrator')
			,array('id' => 2,'title' => 'Merchant')
			,array('id' => 3,'title' => 'Regular Member')
		));
	}
}


class UserTableSeeder extends seeder {
	public function run(){
		DB::table('users')->insert(array(
			array(
				 'id' 		=> 1
				,'role_id' 	=> 2
				,'username' => 'bazaarcorner'
				,'password' => Hash::make('password')
				,'email' 	=> 'admin@bazaarcorner.com'
			)
		));
	}
}

class OrderStatusTableSeeder extends seeder {
      public function run(){
            DB::table('order_status')->delete();
            DB::table('order_status')->insert(array(
                   array('code' => 1000,'text' => 'pending')
                  ,array('code' => 1001,'text' => 'declined')
                  ,array('code' => 1002,'text' => 'refund')
                  ,array('code' => 2000,'text' => 'approved')
            ));
      }
}


class MerchantTableSeeder extends seeder {
	public function run(){
		DB::table('merchants')->insert(array(
			 array('name'=>"bazaarcorner",'username'=>'bazaarcorner','password'=> Hash::make('bazaarcorner'))
                  ,array('name'=>"21dgrs",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"25togo Design",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"2Flamingos",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"2times",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"3 D Intelligent Interior",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"360 DEGREES Weblog",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"360INTEREST",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"3ANDIT",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"43 Cycles",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"4649 Worldwide",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"604 Republic",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"80s Purple",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"A + R Store",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"A Better Tomorrow",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"A Fancy Mess",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"a.louise",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"A.P.C.",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"A8 New York",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"AAA Sports Memorabilia",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Abaci",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Abbacino",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Abe Lincoln Jr",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"AC Gears",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Acapulco Gold",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Accessorability",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Accessory Artists",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ACRIMONY",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ActiveDogToys.com",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Activist Eyewear",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Adore Me",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Adorn",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Aesthetic Correlation",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Aether",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"African Lookbook",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"After Eleven Apparel",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"After Hours Agenda",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Agent Provocateur",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Agnès B.",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"AHAlife",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"AKSEL PARIS",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Al Duca d'Aosta",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Albam Clothing",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alberto Guardiani",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alchemist",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alene Too",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alessi",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alexa Leigh",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alexander McQueen",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"alexandra ferguson",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alfred Julius",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alice + Olivia",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ALKEMi Apparel",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"All Bodyboarders Clothing",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"All Saints",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"AllPopArt",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"alphabowties",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alrightok",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Altadena Works",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Always Fits",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Alyssa Nicole",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Amazon",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Ambiance Design",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"American Apparel",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"American Express",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Ames Bros",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Ames Soles",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"amika",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Amongst Friends",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Amour Vert | eco-fashion",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ampersand AS apostrophe",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Analogue Life",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Anax Clothing",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Angara.com",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"angelrox",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Ani Lee",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Aniika",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ANKR",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"AnOther Magazine",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Another Studio",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Anthem Wares",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Anthropologie",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Anti-Anti",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Anyes Galleani",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ANYGIVENNAME",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Apartment 528",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"apartment therapy",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Apliiq",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Apolis",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Applydea",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Archello",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Archiduchesse",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"AREAWARE",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Argento",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ARIELLE DE PINTO",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Arm the Animals",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Arquebus Clothing",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Arriquitaun",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Art. Lebedev Studio",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Artbird",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Artspace",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Arwey",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ASHKAHN",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ASTALI",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Astrojax",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Atypyk",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"AudioCubes",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Audiowood",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"August Man",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"AViiQ",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"awesomobile",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Axis Maps",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Aylio Fitness",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"b!POP Ventures",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"B&H Photo",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"BAGGU",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Bakerella",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Balsamroot Ranch Jewelry",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"BAM! It's Bernie",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Bamarang UK",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"barley & birch",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Barrett Alley",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Basic Needs",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Bassdrop Clothing",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"BBQs 2U",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"BDDW",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Be A Headcase",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Beardhead",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Unotre",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"uNu",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Up There",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Upon a Fold",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Urban Boulder",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Urban Cricket",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Urban Mercenaries",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Urban Outfitters",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"UrbanDaddy",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Urbantrait",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"UrbanWalls",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"URT Clothing",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"V Nunes",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Valentine Goods",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vaya Bags",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Veda",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Veinticuatridientes",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Veinticuatrodientes",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Velocity Clip",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Velvet Radical",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vertigo Home",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vetted",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"via Licentia",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vicious History",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Victoria Desemone Accessories",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Victoria's Secret",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"VICTORY BRAND",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Viento",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ViewSPORT",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Villains Attic",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vim Beget",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vintage Frames Company",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vintage Mavens",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vintage Style Me",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vinyl Impression",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Viparo",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"virtual FUN ZONE",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"VITAband",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vivarati",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vivienne Kelly",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"vivre",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"vkoo",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vogmask",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vogue",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Volcom",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Volga Verdi",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Volvo",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"VoyVoy Clothing",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vrients",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vusion",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Vvego International",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wall Sushi",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Walnut Studiolo",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wanderlust",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wannekes",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wanted Wallets",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Warby Parker",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"warmi",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"We Are All Smith",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"We Are Selecters",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wellen",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"werd",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"west elm",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"What Goes Around Comes Around",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wheatpaste Art Collective",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"White Collar Crime Clothing",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"WhiteyBoard",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wholesale-dress.net",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wicked Clothes",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wicked Quick",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wicker Paradise",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wildfox Couture",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Williams-Sonoma",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"WineCaddys.com",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wintercheck Factory",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"winterfiber",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wipit",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wishful Thinking Studios",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wishlantern",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wolsey",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wolves Vs Lions",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wood Wood",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Woodies",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Woodwear Sunglasses",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Woolrich",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Woouf",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"WORDS BRAND",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Workerman",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"WorldofWatches.com",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Woven Society",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"WRDBNR",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"WrecordsByMonkey",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wren",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wrong Weather",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"www.theloyalsubjects.com",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"WYMAKEIT",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Wysiwatch",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"X-Mini",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Yanko Design",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"ycollective",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"YLANG | 23",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Yofo",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Yosi Samra",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"You Organic Skincare",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Young & Fierce",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"YOURS shoes/footwear",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Yube Cube",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Yves Saint Laurent",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Zagat",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Zappos",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Zero Gravity",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Zeugari",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Zonkey Boot",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"Zoo Uniform",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
                  ,array('name'=>"zuzii",'username'=>uniqid('user_'),'password'=>Hash::make('password'))
		));
	}
}

class CategoryTableSeeder extends seeder {
	public function run(){
		DB::table('categories')->delete();
		DB::table('categories')->insert(array(
			 array('id'=>'A100','name'=>'Arts and Design','parent_id'=>Null)
                  ,array('id'=>'A101','name'=>'Posters','parent_id'=>'A100')
                  ,array('id'=>'A102','name'=>'Collage','parent_id'=>'A100')
                  ,array('id'=>'A103','name'=>'3D','parent_id'=>'A100')
                  ,array('id'=>'A104','name'=>'Paintings','parent_id'=>'A100')
                  ,array('id'=>'A105','name'=>'Photographs','parent_id'=>'A100')
                  ,array('id'=>'A106','name'=>'Prints','parent_id'=>'A100')
                  ,array('id'=>'A107','name'=>'Carvings','parent_id'=>'A100')
                  ,array('id'=>'A108','name'=>'Sculptures','parent_id'=>'A100')
                  ,array('id'=>'A109','name'=>'Graphic Design','parent_id'=>'A100')
                  ,array('id'=>'A110','name'=>'Product Design','parent_id'=>'A100')
                  ,array('id'=>'A200','name'=>'Automobiles, Boats and Airplanes','parent_id'=>Null)
                  ,array('id'=>'A201','name'=>'Cars','parent_id'=>'A200')
                  ,array('id'=>'A202','name'=>'Motorcycles','parent_id'=>'A200')
                  ,array('id'=>'A203','name'=>'Bikes','parent_id'=>'A200')
                  ,array('id'=>'A204','name'=>'Trucks','parent_id'=>'A200')
                  ,array('id'=>'A205','name'=>'Fixed Wing Airplane','parent_id'=>'A200')
                  ,array('id'=>'A206','name'=>'Helicopters','parent_id'=>'A200')
                  ,array('id'=>'A207','name'=>'Sailboats','parent_id'=>'A200')
                  ,array('id'=>'A208','name'=>'Fishing boats','parent_id'=>'A200')
                  ,array('id'=>'A300','name'=>'Pampered Kids','parent_id'=>Null)
                  ,array('id'=>'A301','name'=>'Toys for Baby','parent_id'=>'A300')
                  ,array('id'=>'A302','name'=>'Baby Boy Clothing','parent_id'=>'A300')
                  ,array('id'=>'A303','name'=>'Baby Girl Clothing ','parent_id'=>'A300')
                  ,array('id'=>'A304','name'=>'For Infants','parent_id'=>'A300')
                  ,array('id'=>'A400','name'=>'Books and Media','parent_id'=>Null)
                  ,array('id'=>'A401','name'=>'Author','parent_id'=>'A400')
                  ,array('id'=>'A402','name'=>'Best Sellers','parent_id'=>'A400')
                  ,array('id'=>'A403','name'=>'New Release','parent_id'=>'A400')
                  ,array('id'=>'A404','name'=>'Pre-Orders','parent_id'=>'A400')
                  ,array('id'=>'A405','name'=>'Text Books','parent_id'=>'A400')
                  ,array('id'=>'A406','name'=>'Magazines','parent_id'=>'A400')
                  ,array('id'=>'A407','name'=>'Story Books','parent_id'=>'A400')
                  ,array('id'=>'A408','name'=>'Music','parent_id'=>'A400')
                  ,array('id'=>'A409','name'=>'Movies','parent_id'=>'A400')
                  ,array('id'=>'A500','name'=>'DIY','parent_id'=>Null)
                  ,array('id'=>'A501','name'=>'Accessories','parent_id'=>'A500')
                  ,array('id'=>'A502','name'=>'Tools','parent_id'=>'A500')
                  ,array('id'=>'A503','name'=>'Women','parent_id'=>'A500')
                  ,array('id'=>'A504','name'=>'Men','parent_id'=>'A500')
                  ,array('id'=>'A505','name'=>'Handicrafts','parent_id'=>'A500')
                  ,array('id'=>'A506','name'=>'Others','parent_id'=>'A500')
                  ,array('id'=>'A600','name'=>'Fashion Women','parent_id'=>Null)
                  ,array('id'=>'A601','name'=>'Accessories','parent_id'=>'A600')
                  ,array('id'=>'A602','name'=>'Bags and Purses','parent_id'=>'A600')
                  ,array('id'=>'A603','name'=>'Coats and Jackets','parent_id'=>'A600')
                  ,array('id'=>'A604','name'=>'Dresses','parent_id'=>'A600')
                  ,array('id'=>'A605','name'=>'Jeans','parent_id'=>'A600')
                  ,array('id'=>'A606','name'=>'Jewelries and Watches','parent_id'=>'A600')
                  ,array('id'=>'A607','name'=>'Jumpers and Cardigans','parent_id'=>'A600')
                  ,array('id'=>'A608','name'=>'Jumpsuits and Playsuits','parent_id'=>'A600')
                  ,array('id'=>'A609','name'=>'Lingerie and Nightwear','parent_id'=>'A600')
                  ,array('id'=>'A610','name'=>'Shoes','parent_id'=>'A600')
                  ,array('id'=>'A611','name'=>'Skirt ','parent_id'=>'A600')
                  ,array('id'=>'A612','name'=>'Shirts','parent_id'=>'A600')
                  ,array('id'=>'A613','name'=>'Shorts','parent_id'=>'A600')
                  ,array('id'=>'A614','name'=>'Socks','parent_id'=>'A600')
                  ,array('id'=>'A615','name'=>'Tights','parent_id'=>'A600')
                  ,array('id'=>'A616','name'=>'Suits and Blazers','parent_id'=>'A600')
                  ,array('id'=>'A617','name'=>'Leathers','parent_id'=>'A600')
                  ,array('id'=>'A618','name'=>'Trousers, Leggings, T-Shirts and Vests','parent_id'=>'A600')
                  ,array('id'=>'A619','name'=>'Tops','parent_id'=>'A600')
                  ,array('id'=>'A620','name'=>'Swimwear','parent_id'=>'A600')
                  ,array('id'=>'A621','name'=>'Sunglasses','parent_id'=>'A600')
                  ,array('id'=>'A700','name'=>'Fashion Men','parent_id'=>Null)
                  ,array('id'=>'A701','name'=>'Accessories and Jewellery','parent_id'=>'A700')
                  ,array('id'=>'A702','name'=>'Coats and Trench coats','parent_id'=>'A700')
                  ,array('id'=>'A703','name'=>'Jackets','parent_id'=>'A700')
                  ,array('id'=>'A704','name'=>'Blazers','parent_id'=>'A700')
                  ,array('id'=>'A705','name'=>'Trousers','parent_id'=>'A700')
                  ,array('id'=>'A706','name'=>'Jeans','parent_id'=>'A700')
                  ,array('id'=>'A707','name'=>'Shirts','parent_id'=>'A700')
                  ,array('id'=>'A708','name'=>'T-shirts','parent_id'=>'A700')
                  ,array('id'=>'A709','name'=>'Sweatshirts','parent_id'=>'A700')
                  ,array('id'=>'A710','name'=>'Knitwear','parent_id'=>'A700')
                  ,array('id'=>'A711','name'=>'Shoes, Boots and Trainers','parent_id'=>'A700')
                  ,array('id'=>'A712','name'=>'Bags','parent_id'=>'A700')
                  ,array('id'=>'A713','name'=>'Accessories','parent_id'=>'A700')
                  ,array('id'=>'A800','name'=>'Gadgets and Electronics','parent_id'=>Null)
                  ,array('id'=>'A801','name'=>'TV and Video','parent_id'=>'A800')
                  ,array('id'=>'A802','name'=>'Home Audio and Theater','parent_id'=>'A800')
                  ,array('id'=>'A803','name'=>'Camera, Photo and Video','parent_id'=>'A800')
                  ,array('id'=>'A804','name'=>'Cell Phones and Accessories','parent_id'=>'A800')
                  ,array('id'=>'A805','name'=>'Video Games','parent_id'=>'A800')
                  ,array('id'=>'A806','name'=>'MP3 Players and Portable Speakers','parent_id'=>'A800')
                  ,array('id'=>'A807','name'=>'Car Electronics and GPS','parent_id'=>'A800')
                  ,array('id'=>'A808','name'=>'Musical Instruments','parent_id'=>'A800')
                  ,array('id'=>'A809','name'=>'Electronics Accessories','parent_id'=>'A800')
                  ,array('id'=>'A810','name'=>'Trade In Your Electronics','parent_id'=>'A800')
                  ,array('id'=>'A811','name'=>'Audio ','parent_id'=>'A800')
                  ,array('id'=>'A900','name'=>'Homewares','parent_id'=>Null)
                  ,array('id'=>'A901','name'=>'Kitchen','parent_id'=>'A900')
                  ,array('id'=>'A902','name'=>'Bedding','parent_id'=>'A900')
                  ,array('id'=>'A903','name'=>'Bath ','parent_id'=>'A900')
                  ,array('id'=>'A904','name'=>'Furnitures','parent_id'=>'A900')
                  ,array('id'=>'A905','name'=>'Décor','parent_id'=>'A900')
                  ,array('id'=>'A906','name'=>'Appliances','parent_id'=>'A900')
                  ,array('id'=>'A907','name'=>'Patio','parent_id'=>'A900')
                  ,array('id'=>'A908','name'=>'Lawn ','parent_id'=>'A900')
                  ,array('id'=>'A909','name'=>'Arts','parent_id'=>'A900')
                  ,array('id'=>'A910','name'=>'Pet Supplies','parent_id'=>'A900')
                  ,array('id'=>'A911','name'=>'Power Tools','parent_id'=>'A900')
                  ,array('id'=>'A912','name'=>'Kitchen Fixtures','parent_id'=>'A900')
                  ,array('id'=>'A913','name'=>'Bath Fixtures','parent_id'=>'A900')
                  ,array('id'=>'A914','name'=>'Hardwares','parent_id'=>'A900')
                  ,array('id'=>'A915','name'=>'Lightings','parent_id'=>'A900')
                  ,array('id'=>'B100','name'=>'Toys','parent_id'=>Null)
                  ,array('id'=>'B101','name'=>'Girl','parent_id'=>'B100')
                  ,array('id'=>'B102','name'=>'Boy','parent_id'=>'B100')
                  ,array('id'=>'B103','name'=>'For Toddlers','parent_id'=>'B100')
                  ,array('id'=>'B104','name'=>'Action Figures','parent_id'=>'B100')
                  ,array('id'=>'B105','name'=>'Dolls','parent_id'=>'B100')
                  ,array('id'=>'B106','name'=>'Plush Toys','parent_id'=>'B100')
                  ,array('id'=>'B107','name'=>'RCs','parent_id'=>'B100')
                  ,array('id'=>'B108','name'=>'Sports and Outdoors','parent_id'=>'B100')
                  ,array('id'=>'B109','name'=>'Educational Toys','parent_id'=>'B100')
                  ,array('id'=>'B110','name'=>'Family Games','parent_id'=>'B100')
                  ,array('id'=>'B200','name'=>'Sporting Equipment','parent_id'=>Null)
                  ,array('id'=>'B201','name'=>'Fitness and Exercise','parent_id'=>'B200')
                  ,array('id'=>'B202','name'=>'Team Sports','parent_id'=>'B200')
                  ,array('id'=>'B203','name'=>'Outdoor Sports','parent_id'=>'B200')
                  ,array('id'=>'B204','name'=>'Water Sports','parent_id'=>'B200')
                  ,array('id'=>'B205','name'=>'Winter Sports','parent_id'=>'B200')
                  ,array('id'=>'B206','name'=>'Golf ','parent_id'=>'B200')
                  ,array('id'=>'B207','name'=>'Basketball Cycling','parent_id'=>'B200')
                  ,array('id'=>'B208','name'=>'Fishing ','parent_id'=>'B200')
                  ,array('id'=>'B209','name'=>'Indoor Sports','parent_id'=>'B200')
                  ,array('id'=>'C100','name'=>'Travel and Tours','parent_id'=>Null)
		));
	}
}

class BrandTableSeeder extends seeder {
      public function run(){
            DB::table('brands')->delete();
            DB::table('brands')->insert(array(
                  /*DIY*/
                   array('id'=>1,'name'=>'21dgrs')
                  ,array('id'=>2,'name'=>'43 Cycles')
                  ,array('id'=>3,'name'=>'Accessorability')
                  ,array('id'=>4,'name'=>'Accessory Artists')
                  ,array('id'=>5,'name'=>'Always Fits')
                  ,array('id'=>6,'name'=>'Alyssa Nicole')
                  ,array('id'=>7,'name'=>'Anti-Anti')
                  ,array('id'=>8,'name'=>'Apolis')
                  ,array('id'=>9,'name'=>'ASTALI')
                  ,array('id'=>10,'name'=>'Vvego International')
                  /*ARTS AND MEDIA*/
                  ,array('id'=>11,'name'=>'25togo Design')
                  ,array('id'=>12,'name'=>'2Flamingos')
                  ,array('id'=>13,'name'=>'3 D Intelligent Interior')
                  ,array('id'=>14,'name'=>'360 DEGREES Weblog')
                  ,array('id'=>15,'name'=>'A + R Store')
                  ,array('id'=>16,'name'=>'AAA Sports Memorabilia')
                  ,array('id'=>17,'name'=>'Abe Lincoln Jr')
                  ,array('id'=>18,'name'=>'AllPopArt')
                  ,array('id'=>19,'name'=>'Alrightok')
                  ,array('id'=>20,'name'=>'Ambiance Design')
                  ,array('id'=>21,'name'=>'Amika')
                  ,array('id'=>23,'name'=>'Another Studio')
                  ,array('id'=>24,'name'=>'Anyes Galleani')
                  ,array('id'=>25,'name'=>'ANYGIVENNAME')
                  ,array('id'=>26,'name'=>'Archello')
                  ,array('id'=>27,'name'=>'AREAWARE')
                  ,array('id'=>28,'name'=>'Art. Lebedev Studio')
                  ,array('id'=>29,'name'=>'Artbird')
                  ,array('id'=>30,'name'=>'Artspace')
                  ,array('id'=>31,'name'=>'Arwey')
                  ,array('id'=>32,'name'=>'ASHKAHN')
                  ,array('id'=>33,'name'=>'Atypyk')
                  ,array('id'=>34,'name'=>'UrbanWalls')
                  ,array('id'=>35,'name'=>'URT Clothing')
                  ,array('id'=>36,'name'=>'Yanko Design')
                  ,array('id'=>37,'name'=>'ycollective')
                  /*FASHION*/
                  ,array('id'=>38,'name'=>'2times')
                  ,array('id'=>39,'name'=>'3ANDIT')
                  ,array('id'=>40,'name'=>'4649worldwide')
                  ,array('id'=>41,'name'=>'80s Purple')
                  ,array('id'=>42,'name'=>'A Better Tomorrow')
                  ,array('id'=>43,'name'=>'A Fancy Mess')
                  ,array('id'=>44,'name'=>'a.louise')
                  ,array('id'=>45,'name'=>'A.P.C.')
                  ,array('id'=>46,'name'=>'A8 New York')
                  ,array('id'=>47,'name'=>'Abaci')
                  ,array('id'=>48,'name'=>'Abbacino')
                  ,array('id'=>49,'name'=>'Acapulco Gold')
                  ,array('id'=>50,'name'=>'Acne')
                  ,array('id'=>51,'name'=>'ACRIMONY')
                  ,array('id'=>52,'name'=>'Activist Eyewear')
                  ,array('id'=>53,'name'=>'Adore Me')
                  ,array('id'=>54,'name'=>'Adorn')
                  ,array('id'=>55,'name'=>'African Lookbook')
                  ,array('id'=>56,'name'=>'After Eleven Apparel')
                  ,array('id'=>57,'name'=>'After Hours Agenda')
                  ,array('id'=>58,'name'=>'Agent Provocateur')
                  ,array('id'=>59,'name'=>'Agnès B.')
                  ,array('id'=>60,'name'=>'AHAlife')
                  ,array('id'=>61,'name'=>'AKSEL PARIS')
                  ,array('id'=>62,'name'=>"Al Duca d'Aosta")
                  ,array('id'=>63,'name'=>'Albam Clothing')
                  ,array('id'=>64,'name'=>'Alberto Guardiani')
                  ,array('id'=>65,'name'=>'Alchemist')
                  ,array('id'=>66,'name'=>'Alene Too')
                  ,array('id'=>67,'name'=>'Alexa Leigh')
                  ,array('id'=>68,'name'=>'Alexander McQueen')
                  ,array('id'=>69,'name'=>'alexandra ferguson')
                  ,array('id'=>70,'name'=>'Alice + Olivia')
                  ,array('id'=>71,'name'=>'ALKEMi Apparel')
                  ,array('id'=>72,'name'=>'All Bodyboarders Clothing')
                  ,array('id'=>73,'name'=>'alphabowties')
                  ,array('id'=>74,'name'=>'Altadena Works')
                  ,array('id'=>75,'name'=>'American Apparel')
                  ,array('id'=>76,'name'=>'Ames Bros')
                  ,array('id'=>77,'name'=>'Ames Soles')
                  ,array('id'=>78,'name'=>'Amongst Friends')
                  ,array('id'=>79,'name'=>'Amour Vert | eco-fashion')
                  ,array('id'=>80,'name'=>'ampersand AS apostrophe')
                  ,array('id'=>81,'name'=>'Angara.com')
                  ,array('id'=>82,'name'=>'angelrox')
                  ,array('id'=>83,'name'=>'Ani Lee')
                  ,array('id'=>84,'name'=>'Aniika')
                  ,array('id'=>85,'name'=>'ANKR')
                  ,array('id'=>86,'name'=>'AnOther Magazine')
                  ,array('id'=>87,'name'=>'Anthem Wares')
                  ,array('id'=>88,'name'=>'Anthropologie')
                  ,array('id'=>89,'name'=>'Apliiq')
                  ,array('id'=>90,'name'=>'Archiduchesse')
                  ,array('id'=>91,'name'=>'Argento')
                  ,array('id'=>92,'name'=>'ARIELLE DE PINTO')
                  ,array('id'=>93,'name'=>'Arm the Animals')
                  ,array('id'=>94,'name'=>'Arquebus Clothing')
                  ,array('id'=>95,'name'=>'Arriquitaun')
                  ,array('id'=>96,'name'=>'BAGGU')
                  ,array('id'=>97,'name'=>'Balsamroot Ranch Jewelry')
                  ,array('id'=>98,'name'=>'Barrett Alley')
                  ,array('id'=>99,'name'=>'Bassdrop Clothing')
                  ,array('id'=>100,'name'=>'Beardhead')
                  ,array('id'=>101,'name'=>'Unotre')
                  ,array('id'=>102,'name'=>'Up There')
                  ,array('id'=>103,'name'=>'Urban Boulder')
                  ,array('id'=>104,'name'=>'Urban Cricket')
                  ,array('id'=>105,'name'=>'Urban Outfitters')
                  ,array('id'=>106,'name'=>'Urbantrait')
                  ,array('id'=>107,'name'=>'V Nunes')
                  ,array('id'=>108,'name'=>'V Nunes')
                  ,array('id'=>109,'name'=>'V Nunes')
                  ,array('id'=>110,'name'=>'Vaya Bags')
                  ,array('id'=>111,'name'=>'Victoria Desemone Accessories')
                  ,array('id'=>112,'name'=>"Victoria's Secret")
                  ,array('id'=>113,'name'=>'ViewSPORT')
                  ,array('id'=>114,'name'=>'Vim Beget')
                  ,array('id'=>115,'name'=>'Vintage Frames Company')
                  ,array('id'=>116,'name'=>'Vintage Style Me')
                  ,array('id'=>117,'name'=>'vivre')
                  ,array('id'=>118,'name'=>'Vogmask')
                  ,array('id'=>119,'name'=>'Vogue')
                  ,array('id'=>120,'name'=>'Volcom')
                  ,array('id'=>121,'name'=>'Volga Verdi')
                  ,array('id'=>122,'name'=>'VoyVoy Clothing')
                  ,array('id'=>123,'name'=>'Vrients')
                  ,array('id'=>124,'name'=>'Wanted Wallets')
                  ,array('id'=>125,'name'=>'Warby Parker')
                  ,array('id'=>126,'name'=>'warmi')
                  ,array('id'=>127,'name'=>'We Are All Smith')
                  ,array('id'=>128,'name'=>'We Are Selecters')
                  ,array('id'=>129,'name'=>'Wellen')
                  ,array('id'=>130,'name'=>'What Goes Around Comes Around')
                  ,array('id'=>131,'name'=>'White Collar Crime Clothing')
                  ,array('id'=>132,'name'=>'Wholesale-dress.net')
                  ,array('id'=>133,'name'=>'Wicked Clothes')
                  ,array('id'=>134,'name'=>'Wicked Quick')
                  ,array('id'=>135,'name'=>'Wildfox Couture')
                  ,array('id'=>136,'name'=>'winterfiber')
                  ,array('id'=>137,'name'=>'Wolsey')
                  ,array('id'=>138,'name'=>'Wolves Vs Lions')
                  ,array('id'=>139,'name'=>'Wood Wood')
                  ,array('id'=>140,'name'=>'Woodwear Sunglasses')
                  ,array('id'=>141,'name'=>'Woolrich')
                  ,array('id'=>142,'name'=>'Woouf')
                  ,array('id'=>143,'name'=>'WORDS BRAND')
                  ,array('id'=>144,'name'=>'WorldofWatches.com')
                  ,array('id'=>145,'name'=>'Woven Society')
                  ,array('id'=>146,'name'=>'WrecordsByMonkey')
                  ,array('id'=>147,'name'=>'Wrong Weather')
                  ,array('id'=>148,'name'=>'Wysiwatch')
                  ,array('id'=>149,'name'=>'YLANG | 23')
                  ,array('id'=>150,'name'=>'Yosi Samra')
                  ,array('id'=>151,'name'=>'You Organic Skincare')
                  ,array('id'=>152,'name'=>'Young & Fierce')
                  ,array('id'=>153,'name'=>'YOURS shoes/footwear')
                  ,array('id'=>154,'name'=>'Zappos')
                  ,array('id'=>155,'name'=>'Zeugari')
                  ,array('id'=>156,'name'=>'Zonkey Boot')
                  ,array('id'=>157,'name'=>'Zoo Uniform')
                  ,array('id'=>158,'name'=>'zuzii')
                  /*GADGETS AND ELECTRONICS*/
                  ,array('id'=>159,'name'=>'AC Gears')
                  ,array('id'=>160,'name'=>'Applydea')
                  ,array('id'=>161,'name'=>'Astrojax')
                  ,array('id'=>162,'name'=>'Audiowood')
                  ,array('id'=>163,'name'=>'AViiQ')
                  ,array('id'=>164,'name'=>'Valentine Goods')
                  ,array('id'=>165,'name'=>'Walnut Studiolo')
                  ,array('id'=>166,'name'=>'werd')
                  ,array('id'=>167,'name'=>'Wishlantern')
                  ,array('id'=>168,'name'=>'X-Mini')
                  ,array('id'=>169,'name'=>'Yofo')
                  ,array('id'=>170,'name'=>'Zero Gravity')
                  /*HOMEWARES*/
                  ,array('id'=>171,'name'=>'Aesthetic Correlation')
                  ,array('id'=>172,'name'=>'Aether')
                  ,array('id'=>173,'name'=>'Alessi')
                  ,array('id'=>174,'name'=>'Analogue Life')
                  ,array('id'=>175,'name'=>'Apartment 528')
                  ,array('id'=>176,'name'=>'apartment therapy')
                  ,array('id'=>177,'name'=>'BBQs 2U')
                  ,array('id'=>178,'name'=>'BDDW')
                  ,array('id'=>179,'name'=>'Veinticuatrodientes')
                  ,array('id'=>180,'name'=>'Vertigo Home')
                  ,array('id'=>181,'name'=>'Vetted')
                  ,array('id'=>182,'name'=>'Victory')
                  ,array('id'=>183,'name'=>'Villains Attic')
                  ,array('id'=>184,'name'=>'Vinyl Impression')
                  ,array('id'=>185,'name'=>'Wannekes')
                  ,array('id'=>186,'name'=>'west elm')
                  ,array('id'=>187,'name'=>'Wheatpaste Art Collective')
                  ,array('id'=>188,'name'=>'WhiteyBoard')
                  ,array('id'=>189,'name'=>'Wicker Paradise')
                  ,array('id'=>190,'name'=>'WineCaddys.com')
                  ,array('id'=>191,'name'=>'Wintercheck Factory')
                  ,array('id'=>192,'name'=>'Woodies')
                  ,array('id'=>193,'name'=>'Workerman')
                  ,array('id'=>194,'name'=>'Yube Cube')
            ));
      }
}

class BrandCategoryTableSeeder extends seeder {
      public function run(){
            DB::table('brand_categories')->delete();
            DB::table('brand_categories')->insert(array(
                  /*DIY*/
                   array('brand_id'=>1,'category_id'=>'A500')
                  ,array('brand_id'=>2,'category_id'=>'A500')
                  ,array('brand_id'=>3,'category_id'=>'A500')
                  ,array('brand_id'=>4,'category_id'=>'A500')
                  ,array('brand_id'=>5,'category_id'=>'A500')
                  ,array('brand_id'=>6,'category_id'=>'A500')
                  ,array('brand_id'=>7,'category_id'=>'A500')
                  ,array('brand_id'=>8,'category_id'=>'A500')
                  ,array('brand_id'=>9,'category_id'=>'A500')
                  ,array('brand_id'=>10,'category_id'=>'A500')
                  /*ARTS AND MEDIA*/
                  ,array('brand_id'=>11,'category_id'=>'A100')
                  ,array('brand_id'=>12,'category_id'=>'A100')
                  ,array('brand_id'=>13,'category_id'=>'A100')
                  ,array('brand_id'=>14,'category_id'=>'A100')
                  ,array('brand_id'=>15,'category_id'=>'A100')
                  ,array('brand_id'=>16,'category_id'=>'A100')
                  ,array('brand_id'=>17,'category_id'=>'A100')
                  ,array('brand_id'=>18,'category_id'=>'A100')
                  ,array('brand_id'=>19,'category_id'=>'A100')
                  ,array('brand_id'=>20,'category_id'=>'A100')
                  ,array('brand_id'=>21,'category_id'=>'A100')
                  ,array('brand_id'=>23,'category_id'=>'A100')
                  ,array('brand_id'=>24,'category_id'=>'A100')
                  ,array('brand_id'=>25,'category_id'=>'A100')
                  ,array('brand_id'=>26,'category_id'=>'A100')
                  ,array('brand_id'=>27,'category_id'=>'A100')
                  ,array('brand_id'=>28,'category_id'=>'A100')
                  ,array('brand_id'=>29,'category_id'=>'A100')
                  ,array('brand_id'=>30,'category_id'=>'A100')
                  ,array('brand_id'=>31,'category_id'=>'A100')
                  ,array('brand_id'=>32,'category_id'=>'A100')
                  ,array('brand_id'=>33,'category_id'=>'A100')
                  ,array('brand_id'=>34,'category_id'=>'A100')
                  ,array('brand_id'=>35,'category_id'=>'A100')
                  ,array('brand_id'=>36,'category_id'=>'A100')
                  ,array('brand_id'=>37,'category_id'=>'A100')
                  /*FASHION WOMEN*/
                  ,array('brand_id'=>38,'category_id'=>'A600')
                  ,array('brand_id'=>39,'category_id'=>'A600')
                  ,array('brand_id'=>40,'category_id'=>'A600')
                  ,array('brand_id'=>41,'category_id'=>'A600')
                  ,array('brand_id'=>42,'category_id'=>'A600')
                  ,array('brand_id'=>43,'category_id'=>'A600')
                  ,array('brand_id'=>44,'category_id'=>'A600')
                  ,array('brand_id'=>45,'category_id'=>'A600')
                  ,array('brand_id'=>46,'category_id'=>'A600')
                  ,array('brand_id'=>47,'category_id'=>'A600')
                  ,array('brand_id'=>48,'category_id'=>'A600')
                  ,array('brand_id'=>49,'category_id'=>'A600')
                  ,array('brand_id'=>50,'category_id'=>'A600')
                  ,array('brand_id'=>51,'category_id'=>'A600')
                  ,array('brand_id'=>52,'category_id'=>'A600')
                  ,array('brand_id'=>53,'category_id'=>'A600')
                  ,array('brand_id'=>54,'category_id'=>'A600')
                  ,array('brand_id'=>55,'category_id'=>'A600')
                  ,array('brand_id'=>56,'category_id'=>'A600')
                  ,array('brand_id'=>57,'category_id'=>'A600')
                  ,array('brand_id'=>58,'category_id'=>'A600')
                  ,array('brand_id'=>59,'category_id'=>'A600')
                  ,array('brand_id'=>60,'category_id'=>'A600')
                  ,array('brand_id'=>61,'category_id'=>'A600')
                  ,array('brand_id'=>62,'category_id'=>"A600")
                  ,array('brand_id'=>63,'category_id'=>'A600')
                  ,array('brand_id'=>64,'category_id'=>'A600')
                  ,array('brand_id'=>65,'category_id'=>'A600')
                  ,array('brand_id'=>66,'category_id'=>'A600')
                  ,array('brand_id'=>67,'category_id'=>'A600')
                  ,array('brand_id'=>68,'category_id'=>'A600')
                  ,array('brand_id'=>69,'category_id'=>'A600')
                  ,array('brand_id'=>70,'category_id'=>'A600')
                  ,array('brand_id'=>71,'category_id'=>'A600')
                  ,array('brand_id'=>72,'category_id'=>'A600')
                  ,array('brand_id'=>73,'category_id'=>'A600')
                  ,array('brand_id'=>74,'category_id'=>'A600')
                  ,array('brand_id'=>75,'category_id'=>'A600')
                  ,array('brand_id'=>76,'category_id'=>'A600')
                  ,array('brand_id'=>77,'category_id'=>'A600')
                  ,array('brand_id'=>78,'category_id'=>'A600')
                  ,array('brand_id'=>79,'category_id'=>'A600')
                  ,array('brand_id'=>80,'category_id'=>'A600')
                  ,array('brand_id'=>81,'category_id'=>'A600')
                  ,array('brand_id'=>82,'category_id'=>'A600')
                  ,array('brand_id'=>83,'category_id'=>'A600')
                  ,array('brand_id'=>84,'category_id'=>'A600')
                  ,array('brand_id'=>85,'category_id'=>'A600')
                  ,array('brand_id'=>86,'category_id'=>'A600')
                  ,array('brand_id'=>87,'category_id'=>'A600')
                  ,array('brand_id'=>88,'category_id'=>'A600')
                  ,array('brand_id'=>89,'category_id'=>'A600')
                  ,array('brand_id'=>90,'category_id'=>'A600')
                  ,array('brand_id'=>91,'category_id'=>'A600')
                  ,array('brand_id'=>92,'category_id'=>'A600')
                  ,array('brand_id'=>93,'category_id'=>'A600')
                  ,array('brand_id'=>94,'category_id'=>'A600')
                  ,array('brand_id'=>95,'category_id'=>'A600')
                  ,array('brand_id'=>96,'category_id'=>'A600')
                  ,array('brand_id'=>97,'category_id'=>'A600')
                  ,array('brand_id'=>98,'category_id'=>'A600')
                  ,array('brand_id'=>99,'category_id'=>'A600')
                  ,array('brand_id'=>100,'category_id'=>'A600')
                  ,array('brand_id'=>101,'category_id'=>'A600')
                  ,array('brand_id'=>102,'category_id'=>'A600')
                  ,array('brand_id'=>103,'category_id'=>'A600')
                  ,array('brand_id'=>104,'category_id'=>'A600')
                  ,array('brand_id'=>105,'category_id'=>'A600')
                  ,array('brand_id'=>106,'category_id'=>'A600')
                  ,array('brand_id'=>107,'category_id'=>'A600')
                  ,array('brand_id'=>108,'category_id'=>'A600')
                  ,array('brand_id'=>109,'category_id'=>'A600')
                  ,array('brand_id'=>110,'category_id'=>'A600')
                  ,array('brand_id'=>111,'category_id'=>'A600')
                  ,array('brand_id'=>112,'category_id'=>"A600")
                  ,array('brand_id'=>113,'category_id'=>'A600')
                  ,array('brand_id'=>114,'category_id'=>'A600')
                  ,array('brand_id'=>115,'category_id'=>'A600')
                  ,array('brand_id'=>116,'category_id'=>'A600')
                  ,array('brand_id'=>117,'category_id'=>'A600')
                  ,array('brand_id'=>118,'category_id'=>'A600')
                  ,array('brand_id'=>119,'category_id'=>'A600')
                  ,array('brand_id'=>120,'category_id'=>'A600')
                  ,array('brand_id'=>121,'category_id'=>'A600')
                  ,array('brand_id'=>122,'category_id'=>'A600')
                  ,array('brand_id'=>123,'category_id'=>'A600')
                  ,array('brand_id'=>124,'category_id'=>'A600')
                  ,array('brand_id'=>125,'category_id'=>'A600')
                  ,array('brand_id'=>126,'category_id'=>'A600')
                  ,array('brand_id'=>127,'category_id'=>'A600')
                  ,array('brand_id'=>128,'category_id'=>'A600')
                  ,array('brand_id'=>129,'category_id'=>'A600')
                  ,array('brand_id'=>130,'category_id'=>'A600')
                  ,array('brand_id'=>131,'category_id'=>'A600')
                  ,array('brand_id'=>132,'category_id'=>'A600')
                  ,array('brand_id'=>133,'category_id'=>'A600')
                  ,array('brand_id'=>134,'category_id'=>'A600')
                  ,array('brand_id'=>135,'category_id'=>'A600')
                  ,array('brand_id'=>136,'category_id'=>'A600')
                  ,array('brand_id'=>137,'category_id'=>'A600')
                  ,array('brand_id'=>138,'category_id'=>'A600')
                  ,array('brand_id'=>139,'category_id'=>'A600')
                  ,array('brand_id'=>140,'category_id'=>'A600')
                  ,array('brand_id'=>141,'category_id'=>'A600')
                  ,array('brand_id'=>142,'category_id'=>'A600')
                  ,array('brand_id'=>143,'category_id'=>'A600')
                  ,array('brand_id'=>144,'category_id'=>'A600')
                  ,array('brand_id'=>145,'category_id'=>'A600')
                  ,array('brand_id'=>146,'category_id'=>'A600')
                  ,array('brand_id'=>147,'category_id'=>'A600')
                  ,array('brand_id'=>148,'category_id'=>'A600')
                  ,array('brand_id'=>149,'category_id'=>'A600')
                  ,array('brand_id'=>150,'category_id'=>'A600')
                  ,array('brand_id'=>151,'category_id'=>'A600')
                  ,array('brand_id'=>152,'category_id'=>'A600')
                  ,array('brand_id'=>153,'category_id'=>'A600')
                  ,array('brand_id'=>154,'category_id'=>'A600')
                  ,array('brand_id'=>155,'category_id'=>'A600')
                  ,array('brand_id'=>156,'category_id'=>'A600')
                  ,array('brand_id'=>157,'category_id'=>'A600')
                  ,array('brand_id'=>158,'category_id'=>'A600')
                  /*FASHION MEN*/
                  ,array('brand_id'=>38,'category_id'=>'A700')
                  ,array('brand_id'=>39,'category_id'=>'A700')
                  ,array('brand_id'=>40,'category_id'=>'A700')
                  ,array('brand_id'=>41,'category_id'=>'A700')
                  ,array('brand_id'=>42,'category_id'=>'A700')
                  ,array('brand_id'=>43,'category_id'=>'A700')
                  ,array('brand_id'=>44,'category_id'=>'A700')
                  ,array('brand_id'=>45,'category_id'=>'A700')
                  ,array('brand_id'=>46,'category_id'=>'A700')
                  ,array('brand_id'=>47,'category_id'=>'A700')
                  ,array('brand_id'=>48,'category_id'=>'A700')
                  ,array('brand_id'=>49,'category_id'=>'A700')
                  ,array('brand_id'=>50,'category_id'=>'A700')
                  ,array('brand_id'=>51,'category_id'=>'A700')
                  ,array('brand_id'=>52,'category_id'=>'A700')
                  ,array('brand_id'=>53,'category_id'=>'A700')
                  ,array('brand_id'=>54,'category_id'=>'A700')
                  ,array('brand_id'=>55,'category_id'=>'A700')
                  ,array('brand_id'=>56,'category_id'=>'A700')
                  ,array('brand_id'=>57,'category_id'=>'A700')
                  ,array('brand_id'=>58,'category_id'=>'A700')
                  ,array('brand_id'=>59,'category_id'=>'A700')
                  ,array('brand_id'=>60,'category_id'=>'A700')
                  ,array('brand_id'=>61,'category_id'=>'A700')
                  ,array('brand_id'=>62,'category_id'=>"A700")
                  ,array('brand_id'=>63,'category_id'=>'A700')
                  ,array('brand_id'=>64,'category_id'=>'A700')
                  ,array('brand_id'=>65,'category_id'=>'A700')
                  ,array('brand_id'=>66,'category_id'=>'A700')
                  ,array('brand_id'=>67,'category_id'=>'A700')
                  ,array('brand_id'=>68,'category_id'=>'A700')
                  ,array('brand_id'=>69,'category_id'=>'A700')
                  ,array('brand_id'=>70,'category_id'=>'A700')
                  ,array('brand_id'=>71,'category_id'=>'A700')
                  ,array('brand_id'=>72,'category_id'=>'A700')
                  ,array('brand_id'=>73,'category_id'=>'A700')
                  ,array('brand_id'=>74,'category_id'=>'A700')
                  ,array('brand_id'=>75,'category_id'=>'A700')
                  ,array('brand_id'=>76,'category_id'=>'A700')
                  ,array('brand_id'=>77,'category_id'=>'A700')
                  ,array('brand_id'=>78,'category_id'=>'A700')
                  ,array('brand_id'=>79,'category_id'=>'A700')
                  ,array('brand_id'=>80,'category_id'=>'A700')
                  ,array('brand_id'=>81,'category_id'=>'A700')
                  ,array('brand_id'=>82,'category_id'=>'A700')
                  ,array('brand_id'=>83,'category_id'=>'A700')
                  ,array('brand_id'=>84,'category_id'=>'A700')
                  ,array('brand_id'=>85,'category_id'=>'A700')
                  ,array('brand_id'=>86,'category_id'=>'A700')
                  ,array('brand_id'=>87,'category_id'=>'A700')
                  ,array('brand_id'=>88,'category_id'=>'A700')
                  ,array('brand_id'=>89,'category_id'=>'A700')
                  ,array('brand_id'=>90,'category_id'=>'A700')
                  ,array('brand_id'=>91,'category_id'=>'A700')
                  ,array('brand_id'=>92,'category_id'=>'A700')
                  ,array('brand_id'=>93,'category_id'=>'A700')
                  ,array('brand_id'=>94,'category_id'=>'A700')
                  ,array('brand_id'=>95,'category_id'=>'A700')
                  ,array('brand_id'=>96,'category_id'=>'A700')
                  ,array('brand_id'=>97,'category_id'=>'A700')
                  ,array('brand_id'=>98,'category_id'=>'A700')
                  ,array('brand_id'=>99,'category_id'=>'A700')
                  ,array('brand_id'=>100,'category_id'=>'A700')
                  ,array('brand_id'=>101,'category_id'=>'A700')
                  ,array('brand_id'=>102,'category_id'=>'A700')
                  ,array('brand_id'=>103,'category_id'=>'A700')
                  ,array('brand_id'=>104,'category_id'=>'A700')
                  ,array('brand_id'=>105,'category_id'=>'A700')
                  ,array('brand_id'=>106,'category_id'=>'A700')
                  ,array('brand_id'=>107,'category_id'=>'A700')
                  ,array('brand_id'=>108,'category_id'=>'A700')
                  ,array('brand_id'=>109,'category_id'=>'A700')
                  ,array('brand_id'=>110,'category_id'=>'A700')
                  ,array('brand_id'=>111,'category_id'=>'A700')
                  ,array('brand_id'=>112,'category_id'=>"A700")
                  ,array('brand_id'=>113,'category_id'=>'A700')
                  ,array('brand_id'=>114,'category_id'=>'A700')
                  ,array('brand_id'=>115,'category_id'=>'A700')
                  ,array('brand_id'=>116,'category_id'=>'A700')
                  ,array('brand_id'=>117,'category_id'=>'A700')
                  ,array('brand_id'=>118,'category_id'=>'A700')
                  ,array('brand_id'=>119,'category_id'=>'A700')
                  ,array('brand_id'=>120,'category_id'=>'A700')
                  ,array('brand_id'=>121,'category_id'=>'A700')
                  ,array('brand_id'=>122,'category_id'=>'A700')
                  ,array('brand_id'=>123,'category_id'=>'A700')
                  ,array('brand_id'=>124,'category_id'=>'A700')
                  ,array('brand_id'=>125,'category_id'=>'A700')
                  ,array('brand_id'=>126,'category_id'=>'A700')
                  ,array('brand_id'=>127,'category_id'=>'A700')
                  ,array('brand_id'=>128,'category_id'=>'A700')
                  ,array('brand_id'=>129,'category_id'=>'A700')
                  ,array('brand_id'=>130,'category_id'=>'A700')
                  ,array('brand_id'=>131,'category_id'=>'A700')
                  ,array('brand_id'=>132,'category_id'=>'A700')
                  ,array('brand_id'=>133,'category_id'=>'A700')
                  ,array('brand_id'=>134,'category_id'=>'A700')
                  ,array('brand_id'=>135,'category_id'=>'A700')
                  ,array('brand_id'=>136,'category_id'=>'A700')
                  ,array('brand_id'=>137,'category_id'=>'A700')
                  ,array('brand_id'=>138,'category_id'=>'A700')
                  ,array('brand_id'=>139,'category_id'=>'A700')
                  ,array('brand_id'=>140,'category_id'=>'A700')
                  ,array('brand_id'=>141,'category_id'=>'A700')
                  ,array('brand_id'=>142,'category_id'=>'A700')
                  ,array('brand_id'=>143,'category_id'=>'A700')
                  ,array('brand_id'=>144,'category_id'=>'A700')
                  ,array('brand_id'=>145,'category_id'=>'A700')
                  ,array('brand_id'=>146,'category_id'=>'A700')
                  ,array('brand_id'=>147,'category_id'=>'A700')
                  ,array('brand_id'=>148,'category_id'=>'A700')
                  ,array('brand_id'=>149,'category_id'=>'A700')
                  ,array('brand_id'=>150,'category_id'=>'A700')
                  ,array('brand_id'=>151,'category_id'=>'A700')
                  ,array('brand_id'=>152,'category_id'=>'A700')
                  ,array('brand_id'=>153,'category_id'=>'A700')
                  ,array('brand_id'=>154,'category_id'=>'A700')
                  ,array('brand_id'=>155,'category_id'=>'A700')
                  ,array('brand_id'=>156,'category_id'=>'A700')
                  ,array('brand_id'=>157,'category_id'=>'A700')
                  ,array('brand_id'=>158,'category_id'=>'A700')
                  /*GADGETS AND ELECTRONICS*/
                  ,array('brand_id'=>159,'category_id'=>'A800')
                  ,array('brand_id'=>160,'category_id'=>'A800')
                  ,array('brand_id'=>161,'category_id'=>'A800')
                  ,array('brand_id'=>162,'category_id'=>'A800')
                  ,array('brand_id'=>163,'category_id'=>'A800')
                  ,array('brand_id'=>164,'category_id'=>'A800')
                  ,array('brand_id'=>165,'category_id'=>'A800')
                  ,array('brand_id'=>166,'category_id'=>'A800')
                  ,array('brand_id'=>167,'category_id'=>'A800')
                  ,array('brand_id'=>168,'category_id'=>'A800')
                  ,array('brand_id'=>169,'category_id'=>'A800')
                  ,array('brand_id'=>170,'category_id'=>'A800')
                  /*HOMEWARES*/
                  ,array('brand_id'=>171,'category_id'=>'A900')
                  ,array('brand_id'=>172,'category_id'=>'A900')
                  ,array('brand_id'=>173,'category_id'=>'A900')
                  ,array('brand_id'=>174,'category_id'=>'A900')
                  ,array('brand_id'=>175,'category_id'=>'A900')
                  ,array('brand_id'=>176,'category_id'=>'A900')
                  ,array('brand_id'=>177,'category_id'=>'A900')
                  ,array('brand_id'=>178,'category_id'=>'A900')
                  ,array('brand_id'=>179,'category_id'=>'A900')
                  ,array('brand_id'=>180,'category_id'=>'A900')
                  ,array('brand_id'=>181,'category_id'=>'A900')
                  ,array('brand_id'=>182,'category_id'=>'A900')
                  ,array('brand_id'=>183,'category_id'=>'A900')
                  ,array('brand_id'=>184,'category_id'=>'A900')
                  ,array('brand_id'=>185,'category_id'=>'A900')
                  ,array('brand_id'=>186,'category_id'=>'A900')
                  ,array('brand_id'=>187,'category_id'=>'A900')
                  ,array('brand_id'=>188,'category_id'=>'A900')
                  ,array('brand_id'=>189,'category_id'=>'A900')
                  ,array('brand_id'=>190,'category_id'=>'A900')
                  ,array('brand_id'=>191,'category_id'=>'A900')
                  ,array('brand_id'=>192,'category_id'=>'A900')
                  ,array('brand_id'=>193,'category_id'=>'A900')
                  ,array('brand_id'=>194,'category_id'=>'A900')
            ));
      }
}